// jobs.js — All active job offers
// Used by offers.js and apply.js

export const JOBS = [
  {
    id: 1,
    company: "Assets",
    title: "Appointment Setter FT",
    salary: "15K + 6K commission + 2K transport",
    location: "Nasr City",
    workType: "on-site",
    shift: "4pm – 5am",
    englishLevel: "B2+",
    experience: "none",
    nationality: "egyptians-only",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 2,
    company: "Assets",
    title: "B2B Morning Shift",
    salary: "17K + 3K KPI up to 40K",
    location: "Nasr City",
    workType: "on-site",
    shift: "10:45am – 8pm",
    englishLevel: "B2+",
    experience: "none",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 3,
    company: "Assets",
    title: "Customer Support Back Office",
    salary: "12K + commission",
    location: "Nasr City",
    workType: "on-site",
    shift: "4pm – 5am",
    englishLevel: "B2+",
    experience: "none",
    nationality: "egyptians-only",
    gender: "females-only",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 4,
    company: "TTC",
    title: "Telesales US Account",
    salary: "12K + unlimited commission + 1K KPI",
    location: "Nasr City",
    workType: "on-site",
    shift: "3pm – 11pm",
    englishLevel: "B2+",
    experience: "none",
    nationality: "egyptians-only",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: 28,
    status: "active"
  },
  {
    id: 5,
    company: "Aces",
    title: "Telesales Medical US",
    salary: "10K + 2K KPI + up to 15K commission",
    location: "Abbasiya",
    workType: "on-site",
    shift: "3:30pm – 11:30pm",
    englishLevel: "B2",
    experience: "none",
    nationality: "egyptians-only",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: 26,
    status: "active"
  },
  {
    id: 6,
    company: "Aces",
    title: "Part-time Telesales",
    salary: "7K + commission",
    location: "Abbasiya",
    workType: "on-site",
    shift: "Rotational",
    englishLevel: "B2",
    experience: "none",
    nationality: "egyptians-only",
    gender: "all",
    employmentType: "part-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 7,
    company: "BIS",
    title: "Telesales USA",
    salary: "10K + up to 20K commission",
    location: "Nasr City",
    workType: "on-site",
    shift: "3pm – 11pm",
    englishLevel: "B2+",
    experience: "none",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 8,
    company: "Cataleads",
    title: "ISA Appointment Setter",
    salary: "$3.5–$5/hr + uncapped bonus (avg 40K–60K EGP)",
    location: "Nasr City",
    workType: "on-site",
    shift: "5pm – 2am",
    englishLevel: "C1",
    experience: "6months+",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: 30,
    status: "active"
  },
  {
    id: 9,
    company: "Cataleads",
    title: "Real Estate Cold Caller",
    salary: "$3/hr + bonuses",
    location: "Nasr City",
    workType: "on-site",
    shift: "5pm – 2am",
    englishLevel: "C1",
    experience: "1year+",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: 30,
    status: "active"
  },
  {
    id: 10,
    company: "Creative Basket",
    title: "Travel Advisor Telesales",
    salary: "$250–$400 + commission",
    location: "Nasr City",
    workType: "on-site",
    shift: "4pm – 1am",
    englishLevel: "B2+",
    experience: "6months+",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 11,
    company: "Nexuara",
    title: "Cold-Calling Agent",
    salary: "1K EGP per deal (commission-based)",
    location: "Gisr El Suez",
    workType: "on-site",
    shift: "4pm – 12am",
    englishLevel: "B2",
    experience: "none",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 12,
    company: "Synergistic",
    title: "Telesales Paid Internship",
    salary: "16K + commission",
    location: "Nasr City",
    workType: "on-site",
    shift: "2am – 10am",
    englishLevel: "B2",
    experience: "none",
    nationality: "non-african",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: 25,
    status: "active"
  },
  {
    id: 13,
    company: "Symbios",
    title: "BDR Business Development",
    salary: "Up to 16.5K + USD commissions",
    location: "Nasr City",
    workType: "on-site",
    shift: "11:45pm – 8am",
    englishLevel: "C1",
    experience: "1year+",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "grads-only",
    maxAge: null,
    status: "active"
  },
  {
    id: 14,
    company: "Geeky CX",
    title: "Debt Settlement Negotiator",
    salary: "15K + up to 10K bonus",
    location: "Sheikh Zayed",
    workType: "on-site",
    shift: "7pm – 4am",
    englishLevel: "C1",
    experience: "1year+",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "grads-only",
    maxAge: null,
    status: "active"
  },
  {
    id: 15,
    company: "Leadbull",
    title: "Telesales Canadian Account FT",
    salary: "15K + 5K KPI + spiffs",
    location: "Zahraa El Maadi",
    workType: "on-site",
    shift: "4pm – 1am",
    englishLevel: "B2+",
    experience: "none",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 16,
    company: "Leadbull",
    title: "Telesales Canadian Account WFH",
    salary: "15K + 5K KPI",
    location: "WFH",
    workType: "wfh",
    shift: "3pm – 12am",
    englishLevel: "B2+",
    experience: "none",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 17,
    company: "REZ",
    title: "Real Estate Cold Caller WFH",
    salary: "$250 basic + $100 KPI + bonuses",
    location: "WFH",
    workType: "wfh",
    shift: "9hr shift Mon–Fri",
    englishLevel: "B2",
    experience: "6months+",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 18,
    company: "Outsourcing 4u",
    title: "Telesales UK Agent",
    salary: "Up to 16K + unlimited commission",
    location: "Maadi",
    workType: "on-site",
    shift: "11:30am – 7:45pm",
    englishLevel: "B2",
    experience: "none",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 19,
    company: "Outsourcing 4u",
    title: "HR Generalist",
    salary: "10K",
    location: "Maadi",
    workType: "on-site",
    shift: "11:30am – 7:45pm",
    englishLevel: "B2+",
    experience: "6months+",
    nationality: "all",
    gender: "females-only",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 20,
    company: "Outsourcing 4u",
    title: "Social Media Specialist",
    salary: "7.5K",
    location: "Maadi",
    workType: "on-site",
    shift: "12pm – 8:15pm",
    englishLevel: "B2",
    experience: "3months+",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 21,
    company: "Outsourcing 4u",
    title: "HR Recruiter",
    salary: "8K",
    location: "Maadi",
    workType: "on-site",
    shift: "12:15pm – 8:30pm",
    englishLevel: "B2+",
    experience: "3months+",
    nationality: "all",
    gender: "females-only",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 22,
    company: "Winirix",
    title: "Appointment Setter WFH",
    salary: "15K + 2K KPI",
    location: "WFH",
    workType: "wfh",
    shift: "5pm – 2am",
    englishLevel: "B2",
    experience: "6months+",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  },
  {
    id: 23,
    company: "Launch Pad",
    title: "Sales Agent Travel",
    salary: "12K + up to 10K commission",
    location: "Sheikh Zayed",
    workType: "on-site",
    shift: "3:30pm – 12:30am",
    englishLevel: "C1",
    experience: "none",
    nationality: "egyptians-only",
    gender: "all",
    employmentType: "full-time",
    graduation: "grads-only",
    maxAge: 30,
    status: "active"
  },
  {
    id: 24,
    company: "Dial Expert",
    title: "Tax Sales Closer WFH",
    salary: "15K + $10–$15 per deal",
    location: "WFH",
    workType: "wfh",
    shift: "6pm – 3am",
    englishLevel: "B2+",
    experience: "6months+",
    nationality: "all",
    gender: "all",
    employmentType: "full-time",
    graduation: "all",
    maxAge: null,
    status: "active"
  }
];
